### ISSUE TITLE
GPU-Viewer won't open on openSUSE due to missing 'click' module in Python

### ISSUE THREAD

**Issue by kreaninw** [arunsivaramanneo/GPU-Viewer#46] opened 2022-08-03 09:14 UTC
After built and installed the app, it won't open with `ModuleNotFoundError: No module named 'click'` error in the terminal.

This can be fixed by installing the click module: `pip install click`.

I am on openSUSE Tumbleweed.

**Comment by arunsivaramanneo** [comment] 2022-08-03 23:49
Thank you ... so the issue is resolved ?

**Comment by kreaninw** [comment] 2022-08-03 23:52
> Thank you ... so the issue is resolved ?

Yes, the issue is resolved. I can use the app without any issue.

**Comment by arunsivaramanneo** [comment] 2022-08-04 13:57
Thanks,  closing the issue

**Comment by arunsivaramanneo** [comment] 2022-08-04 13:58
Issue resolved

**Closed by arunsivaramanneo** 2022-08-04 13:57 UTC
