### ISSUE TITLE
AppImage release

### ISSUE THREAD

**Issue by JaxxArmstrong** [arunsivaramanneo/GPU-Viewer#35] opened 2021-09-27 09:14 UTC
Thank you for a great application. May I recommend you package it in a AppImage format so it's easy for any Linux user to use it, please.

AppImages are very easy to create and can be set up to be automatically packaged on new releases, if choose to do so.

**Comment by Hasshu** [comment] 2021-12-10 16:19
See also #14.

**Comment by arunsivaramanneo** [comment] 2024-02-09 22:38
duplicate of #14

**Closed by arunsivaramanneo** 2024-02-09 22:38 UTC
