### ISSUE TITLE
<wayland> main window is larger than screen size

### ISSUE THREAD

**Issue by IlgazC** [arunsivaramanneo/GPU-Viewer#56] opened 2023-01-03 02:11 UTC
I have an Intel i5500 running under Wayland/KDE. When I launch GPUViewer flatpak, I can't see minimize/restore/close buttons. When I checked it out, it appeared that the GPUViewer window is larger than the monitor size (1920x1080). When I click "maximize" it doesn't help, it seems like it is somehow getting the screen size wrong.

![image](https://user-images.githubusercontent.com/19528613/210291679-d7577af3-2961-4804-86a2-324f2aeb3d04.png)

**Comment by arunsivaramanneo** [comment] 2023-01-03 04:16
thanks for raising this issue .. i will look into it and update ... can i know which distro is it

**Comment by IlgazC** [comment] 2023-01-03 05:17
openSUSE Tumbleweed

**Comment by arunsivaramanneo** [comment] 2023-01-03 10:29
I have checked this again on Ubuntu 22.04 wayland with Flatpak and it is working fine. Are you using Multi Monitor setup ?

**Comment by IlgazC** [comment] 2023-01-03 18:38
Yes, dual monitor. One laptop's display (1360x768, left) and 1920x1080 main monitor. GPU Viewer launches on 1920x1080 one.

**Comment by arunsivaramanneo** [comment] 2023-01-03 21:44
can you run this command **xdpyinfo | awk '/dimensions/{print $2}** and let me know what output are you getting

**Comment by IlgazC** [comment] 2023-01-05 04:32
xdpyinfo | awk '/dimensions/{print $2}'
3286x1080

**Comment by arunsivaramanneo** [comment] 2023-01-05 08:19
thanks a lot , now i  know what the issue is

**Comment by arunsivaramanneo** [comment] 2023-01-05 11:43
I have made some work-around for this and have pushed the code , not sure if you can clone it and test it

**Comment by IlgazC** [comment] 2023-01-06 09:34
I did a very quick&dirty compile here. It seems that the issue was fixed. I see a normal sized window and when I maximize, it maximizes to screen size correctly.
![image](https://user-images.githubusercontent.com/19528613/210973191-91471863-445b-496d-8329-aacfbba83d2a.png)

**Comment by arunsivaramanneo** [comment] 2023-01-06 17:17
Thanks a lot for your help in getting this tested , i will push a new
release soon.

**Comment by IlgazC** [comment] 2023-01-19 05:28
> Thanks a lot for your help in getting this tested , i will push a new release soon.
I just had it updated on Flatpak and the issue is indeed fixed. I assume you don't close the bug because it is a workaround? Thank you.

**Comment by arunsivaramanneo** [comment] 2023-01-24 20:36
I have fixed the issue in new Release v2.20, if it looks Ok .. can you please close the issue

**Closed** 2023-01-25 08:02 UTC
Labels: bug
