### ISSUE TITLE
support appimage,

### ISSUE THREAD

**Issue by newyorkthink** [arunsivaramanneo/GPU-Viewer#78] opened 2024-02-06 05:11 UTC

**Comment by arunsivaramanneo** [comment] 2024-02-09 22:37
duplicate of #35

**Closed by arunsivaramanneo** 2024-02-09 22:37 UTC

**Comment by arunsivaramanneo** [comment] 2024-02-17 07:48
@newyorkthink I gave a shot at appImage and got one working on my machine ... please check if this works

https://github.com/arunsivaramanneo/GPU-Viewer/releases/download/v3.02/GPU-Viewer-x86_64.AppImage
